name: Testing
on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10" ]
    # defaults: 
    #   run:
    #     shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          # Install a specific version of uv.
          version: "0.5.4"
  
      - name: Install dependencies
        run: |
          python -m pip install uv
          uv venv -p ${{ matrix.python-version }}
          uv pip install -e .[test,web]

      - name: Download test file
        run: |
          wget "https://filedn.eu/loRXwzWCNnU4XoFPGbllt1y/datafile_1.ptu" -O tests/test_data/input/ds1/datafile_1.ptu

      - name: Activate virtualenv
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      # - name: Install in editable mode with test requirements
      #   run: uv pip install -p ${{ matrix.python-version }} -e .[test]

      - name: Run tests
        run: |
          pytest tests/
